[package]
name = "bheretic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6.0"
anyhow = "1.0.52"
byteorder = "1.4.3"
